### ISSUE TITLE
noarch build failing

### ISSUE THREAD

**Issue by carlodri** [conda-forge/black-feedstock#1]
@conda-forge/core is it normal that the noarch build is failing?

**Comment by ocefpaf** [comment]
Looks like all of conda-forge's CircleCI builds are broken at the moment. I'll investigate but I'm sure @conda-forge/core members are already on top on this.

**Comment by jakirkham** [comment]
Even though this is cosmetic, went ahead and triggered a rebuild, which passed. Guess we are good to close?
