### ISSUE TITLE
Add black to the default channel

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/black-feedstock#9]
@msarahan and @jjhelmus `black` is becoming more and more important to the python ecosystem and it would be nice to have in the default channel for those who want to avoid `pip` installing or using a third party channel. What do you think?

**Comment by marcelotrevisani** [comment]
Related to https://github.com/conda/conda-build/pull/3631 as well

**Comment by msarahan** [comment]
Let's do it.

**Comment by msarahan** [comment]
going up shortly.  Closing.
